# The first makefile with one simple target that should assemble 
# an executable file from all existing files in the directory

my_calc: main.c calcint.c calcdbl.c
	gcc -Wall -Werror -g -o my_calc main.c calcint.c calcdbl.c -lm